name: Deploy Automatico su Staging

on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: Deploy su Hostinger (staging)
    runs-on: ubuntu-latest
    steps:
      - name: Ottieni il codice più recente
        uses: actions/checkout@v4

      - name: Sincronizza i file via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/
